target 'UMengDemo' do
    # U-Share SDK UI模块（分享面板，建议添加）
    # pod ‘UMengUShare/UI‘ 这里友盟拷贝过来的引号有问题
    pod 'UMengUShare/UI'
    
    # 集成新浪微博
    pod 'UMengUShare/Social/Sina'

    # 集成微信
    pod 'UMengUShare/Social/WeChat'

    # 集成QQ
    pod 'UMengUShare/Social/QQ'

    # 集成短信
    pod 'UMengUShare/Social/SMS'
end
